/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElIcon: typeof import('element-plus/es')['ElIcon']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    IconSvgSpinners180Ring: typeof import('~icons/svg-spinners/180-ring')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WelcomeItem: typeof import('./components/WelcomeItem.vue')['default']
  }
}
